### ISSUE TITLE
Carriers enum is almost empty

### ISSUE THREAD

**Issue by frogcrush** [goshippo/shippo-csharp-sdk#13]
Judging by https://docs.goshippo.com/shippoapi/public-api/#tag/Carriers, there should be a lot of carriers supported by the API. However, only three are currently listed under the Carriers enum. This makes it hard to validate that a tracking status matches an appropriate carrier.

**Comment by 2ynn** [comment]
@frogcrush which Carriers enum are you referring to exactly? 

From what I can see the `CarriersEnum` stored in `Shippo/Models/Components` seems to be properly populated:
https://github.com/frogcrush/shippo-csharp-sdk/blob/c986d9bba88524e813549f22cfd3e4e881107f0f/Shippo/Models/Components/CarriersEnum.cs#L85

**Comment by rkeur7** [comment]
Closing this since the issue is stale and cannot be verified.
